version: '3.0'

services:
  estacionamento-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estacionamento-app
    entrypoint : sh -c 'npm install --frozen-lockfile && npm run estacionamento:dev'
    depends_on:
      - mysqldb
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=paswword
      - DATABASE_DB=estacionamento
    networks:
      - api-networks
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - api-networks
    environment:
      MYSQL_ROOT_PASSWORD: password,
      MYSQL_DATABASE: estacionamento
    ports:
      - "${MYSQLPORT}:${MYSQLPORT}"
    volumes:
      - mysqldatabase:/data/db

networks:
  api-networks:
volumes:
  mysqldatabase: